compile MagnetsandInductors.md MagnetsandInductors.html
compile MagnetsandInductors.md MagnetsandInductors.html
compile MagnetsandInductors.md MagnetsandInductors.html
compile MagnetsandInductors.md MagnetsandInductors.html
compile MagnetsandInductors.md MagnetsandInductors.html
compile MagnetsandInductors.md MagnetsandInductors.html
exit
